#!/bin/bash
# Qubes SDP Qrexec Policy Generator
# Generates and manages qrexec policies for SDP qubes

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

MODE="${1:-show}"

usage() {
    cat << EOF
Qubes SDP Qrexec Policy Generator

Usage: $(basename "$0") [MODE]

Modes:
    show        Show current policies (default)
    generate    Generate recommended policies
    apply       Apply generated policies
    backup      Backup existing policies

Examples:
    $(basename "$0") show
    $(basename "$0") generate
    $(basename "$0") apply

EOF
}

# Check dom0
if [ "$(hostname)" != "dom0" ]; then
    echo -e "${RED}ERROR: Must run in dom0${NC}"
    exit 1
fi

# Header
show_header() {
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}           ${BLUE}Qubes SDP Policy Generator${NC}                      ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo
}

# Show current policies
show_policies() {
    show_header
    echo -e "${BLUE}Current Qrexec Policies:${NC}"
    echo

    # File copy policy
    if [ -f /etc/qubes-rpc/policy/qubes.Filecopy ]; then
        echo -e "${CYAN}File Copy (qubes.Filecopy):${NC}"
        grep -E "(work|vault|anon|untrusted)" /etc/qubes-rpc/policy/qubes.Filecopy 2>/dev/null || \
            echo "  No SDP-specific rules"
        echo
    fi

    # Clipboard policy
    if [ -f /etc/qubes-rpc/policy/qubes.ClipboardPaste ]; then
        echo -e "${CYAN}Clipboard Paste (qubes.ClipboardPaste):${NC}"
        grep -E "(work|vault|anon|untrusted)" /etc/qubes-rpc/policy/qubes.ClipboardPaste 2>/dev/null || \
            echo "  No SDP-specific rules"
        echo
    fi

    # GPG policy
    if [ -f /etc/qubes-rpc/policy/qubes.Gpg ]; then
        echo -e "${CYAN}GPG (qubes.Gpg):${NC}"
        grep -E "(work|vault)" /etc/qubes-rpc/policy/qubes.Gpg 2>/dev/null || \
            echo "  No SDP-specific rules"
        echo
    fi

    # SSH Agent policy
    if [ -f /etc/qubes-rpc/policy/qubes.SshAgent ]; then
        echo -e "${CYAN}SSH Agent (qubes.SshAgent):${NC}"
        grep -E "(work|vault)" /etc/qubes-rpc/policy/qubes.SshAgent 2>/dev/null || \
            echo "  No SDP-specific rules"
        echo
    fi
}

# Generate recommended policies
generate_policies() {
    show_header
    echo -e "${BLUE}Generating Recommended Policies...${NC}"
    echo

    POLICY_DIR="/tmp/qubes-sdp-policies"
    mkdir -p "${POLICY_DIR}"

    # File Copy Policy
    cat > "${POLICY_DIR}/qubes.Filecopy" << 'EOF'
# Qubes SDP File Copy Policies
# Generated by qubes-policy-generator.sh

# Allow work to vault (secure document storage)
work vault allow

# Ask before copying from untrusted to work
untrusted work ask

# Deny untrusted to vault (prevent contamination)
untrusted vault deny

# Deny anon to vault
anon vault deny

# Allow vault to work (extract documents)
vault work ask
EOF

    echo -e "${GREEN}✓${NC} Generated qubes.Filecopy"

    # Clipboard Policy
    cat > "${POLICY_DIR}/qubes.ClipboardPaste" << 'EOF'
# Qubes SDP Clipboard Policies
# Generated by qubes-policy-generator.sh

# Ask before pasting to vault
work vault ask
vault work ask

# Deny clipboard from untrusted to sensitive qubes
untrusted vault deny
untrusted work deny
EOF

    echo -e "${GREEN}✓${NC} Generated qubes.ClipboardPaste"

    # GPG Policy (if split-GPG enabled)
    cat > "${POLICY_DIR}/qubes.Gpg" << 'EOF'
# Qubes SDP Split-GPG Policies
# Generated by qubes-policy-generator.sh

# Allow work to use GPG keys in vault
work vault ask

# Deny all others
* vault deny
EOF

    echo -e "${GREEN}✓${NC} Generated qubes.Gpg"

    # SSH Agent Policy (if split-SSH enabled)
    cat > "${POLICY_DIR}/qubes.SshAgent" << 'EOF'
# Qubes SDP Split-SSH Policies
# Generated by qubes-policy-generator.sh

# Allow work to use SSH keys in vault
work vault ask

# Deny all others
* vault deny
EOF

    echo -e "${GREEN}✓${NC} Generated qubes.SshAgent"

    echo
    echo -e "${BLUE}Policy files generated in: ${POLICY_DIR}${NC}"
    echo
    echo -e "${YELLOW}Review the files before applying!${NC}"
    echo -e "To apply: $(basename "$0") apply"
    echo
}

# Backup existing policies
backup_policies() {
    show_header
    echo -e "${BLUE}Backing up existing policies...${NC}"
    echo

    BACKUP_DIR="/var/backups/qubes-policies-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "${BACKUP_DIR}"

    POLICIES=("qubes.Filecopy" "qubes.ClipboardPaste" "qubes.Gpg" "qubes.SshAgent")

    for policy in "${POLICIES[@]}"; do
        if [ -f "/etc/qubes-rpc/policy/${policy}" ]; then
            cp "/etc/qubes-rpc/policy/${policy}" "${BACKUP_DIR}/"
            echo -e "${GREEN}✓${NC} Backed up ${policy}"
        fi
    done

    echo
    echo -e "${GREEN}Backup created: ${BACKUP_DIR}${NC}"
    echo
}

# Apply policies
apply_policies() {
    show_header

    POLICY_DIR="/tmp/qubes-sdp-policies"

    if [ ! -d "${POLICY_DIR}" ]; then
        echo -e "${RED}ERROR: No generated policies found${NC}"
        echo -e "Run: $(basename "$0") generate"
        exit 1
    fi

    echo -e "${BLUE}Applying Policies...${NC}"
    echo

    # Backup first
    echo -e "${YELLOW}Creating backup...${NC}"
    backup_policies

    # Apply each policy
    for policy_file in "${POLICY_DIR}"/*; do
        if [ ! -f "${policy_file}" ]; then
            continue
        fi

        POLICY_NAME=$(basename "${policy_file}")
        DEST="/etc/qubes-rpc/policy/${POLICY_NAME}"

        # Check if policy file exists
        if [ -f "${DEST}" ]; then
            # Append to existing file
            echo -e "${YELLOW}ℹ${NC} Appending to existing ${POLICY_NAME}"

            # Add separator
            echo "" >> "${DEST}"
            echo "# === Qubes SDP Policies (Added $(date)) ===" >> "${DEST}"

            # Append new rules (avoid duplicates)
            while IFS= read -r line; do
                # Skip comments and empty lines
                if [[ "${line}" =~ ^[[:space:]]*# ]] || [[ -z "${line}" ]]; then
                    echo "${line}" >> "${DEST}"
                    continue
                fi

                # Check if rule already exists
                if grep -Fxq "${line}" "${DEST}" 2>/dev/null; then
                    echo -e "  ${YELLOW}!${NC} Rule already exists: ${line}"
                else
                    echo "${line}" >> "${DEST}"
                    echo -e "  ${GREEN}+${NC} Added: ${line}"
                fi
            done < "${policy_file}"
        else
            # Create new file
            echo -e "${GREEN}✓${NC} Creating new ${POLICY_NAME}"
            cp "${policy_file}" "${DEST}"
        fi

        # Set permissions
        chmod 664 "${DEST}"
    done

    echo
    echo -e "${GREEN}Policies applied successfully${NC}"
    echo
    echo -e "${BLUE}NOTE:${NC} Some policies may require qrexec daemon restart:"
    echo -e "  systemctl restart qubes-qrexec-policy-daemon"
    echo
}

# Show policy syntax help
show_help() {
    show_header
    echo -e "${BLUE}Qrexec Policy Syntax:${NC}"
    echo

    cat << EOF
Format: SOURCE DESTINATION ACTION [OPTIONS]

SOURCE:      Qube name or * (any qube)
DESTINATION: Qube name, @dispvm, or @default
ACTION:      allow, deny, ask

Examples:
  work vault allow          # Always allow work → vault
  work vault ask            # Ask user for work → vault
  untrusted vault deny      # Always deny untrusted → vault
  * vault deny              # Deny all qubes to vault

Special Keywords:
  @dispvm      - Disposable VM
  @default     - Default behavior
  @anyvm       - Any VM
  @adminvm     - dom0/Admin VM

Options:
  user=<name>      - Specific user
  target=<name>    - Override destination

Policy Files:
  qubes.Filecopy       - File copy operations
  qubes.ClipboardPaste - Clipboard paste operations
  qubes.Gpg            - GPG operations
  qubes.SshAgent       - SSH agent operations

Location: /etc/qubes-rpc/policy/

EOF
}

# Main
case "${MODE}" in
    show)
        show_policies
        ;;
    generate)
        generate_policies
        ;;
    apply)
        apply_policies
        ;;
    backup)
        backup_policies
        ;;
    help|-h|--help)
        show_help
        ;;
    *)
        echo -e "${RED}Unknown mode: ${MODE}${NC}"
        echo
        usage
        exit 1
        ;;
esac
